export { Home } from './Home/Home.page'
export { Products } from './Products/Products.page'
export { Basket } from './Basket/Basket.page'
export { Product } from './Product/Product.page'
export { PaymentResult } from './PaymentResult/PaymentResult.page'
export { Checkout } from './Checkout/Checkout.page'
